using Azure.Search.Documents.Indexes;
using Azure.Search.Documents.Indexes.Models;

namespace RagIngestionApp.Models;

/// <summary>
/// One cached question-answer pair stored in the rag-answer-cache Azure AI Search index.
/// The vector field enables similarity lookup: when a new question arrives, its embedding
/// is compared against all cached question embeddings. If the cosine similarity is above
/// the threshold, the stored Answer is returned without calling the AI model.
/// </summary>
public class CacheEntry
{
    [SimpleField(IsKey = true)]
    public string Id { get; set; } = "";

    /// <summary>The original question text as asked. Stored for logging/debugging.</summary>
    [SearchableField(AnalyzerName = LexicalAnalyzerName.Values.EnLucene)]
    public string QuestionText { get; set; } = "";

    /// <summary>The full grounded answer previously generated by the RAG pipeline.</summary>
    /// Fields are retrievable by default in Azure AI Search.
    /// SimpleField has no IsRetrievable property — use IsHidden = true to hide a field.
    [SimpleField]
    public string Answer { get; set; } = "";

    /// <summary>ISO-8601 timestamp when this entry was first cached.</summary>
    [SimpleField(IsFilterable = true, IsSortable = true)]
    public DateTimeOffset CachedAt { get; set; }

    /// <summary>Number of times this cached answer was returned instead of calling the model.</summary>
    [SimpleField(IsFilterable = true, IsSortable = true)]
    public int HitCount { get; set; }

    /// <summary>
    /// 1536-dimension embedding of QuestionText.
    /// Used for semantic similarity lookup — the heart of the caching mechanism.
    /// </summary>
    [VectorSearchField(
        VectorSearchDimensions  = 1536,
        VectorSearchProfileName = "cache-vector-profile")]
    public float[] QuestionVector { get; set; } = [];
}
